/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class domain_engine_quantum_maps_NativeMap */

#ifndef _Included_domain_engine_quantum_maps_NativeMap
#define _Included_domain_engine_quantum_maps_NativeMap
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     domain_engine_quantum_maps_NativeMap
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_domain_engine_quantum_maps_NativeMap_init
  (JNIEnv *, jobject);

/*
 * Class:     domain_engine_quantum_maps_NativeMap
 * Method:    _clear
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_domain_engine_quantum_maps_NativeMap__1clear
  (JNIEnv *, jobject, jlong);

/*
 * Class:     domain_engine_quantum_maps_NativeMap
 * Method:    _containsKey
 * Signature: (JLjava/lang/Object;)Z
 */
JNIEXPORT jboolean JNICALL Java_domain_engine_quantum_maps_NativeMap__1containsKey
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     domain_engine_quantum_maps_NativeMap
 * Method:    _containsValue
 * Signature: (JLjava/lang/Object;)Z
 */
JNIEXPORT jboolean JNICALL Java_domain_engine_quantum_maps_NativeMap__1containsValue
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     domain_engine_quantum_maps_NativeMap
 * Method:    _entrySet
 * Signature: (J)Ljava/util/Set;
 */
JNIEXPORT jobject JNICALL Java_domain_engine_quantum_maps_NativeMap__1entrySet
  (JNIEnv *, jobject, jlong);

/*
 * Class:     domain_engine_quantum_maps_NativeMap
 * Method:    _get
 * Signature: (JLjava/lang/Object;)Ldomain/engine/math/Complex;
 */
JNIEXPORT jobject JNICALL Java_domain_engine_quantum_maps_NativeMap__1get
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     domain_engine_quantum_maps_NativeMap
 * Method:    _isEmpty
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_domain_engine_quantum_maps_NativeMap__1isEmpty
  (JNIEnv *, jobject, jlong);

/*
 * Class:     domain_engine_quantum_maps_NativeMap
 * Method:    _keySet
 * Signature: (J)Ljava/util/Set;
 */
JNIEXPORT jobject JNICALL Java_domain_engine_quantum_maps_NativeMap__1keySet
  (JNIEnv *, jobject, jlong);

/*
 * Class:     domain_engine_quantum_maps_NativeMap
 * Method:    _put
 * Signature: (JLdomain/engine/quantum/ClassicState;Ldomain/engine/math/Complex;)Ldomain/engine/math/Complex;
 */
JNIEXPORT jobject JNICALL Java_domain_engine_quantum_maps_NativeMap__1put
  (JNIEnv *, jobject, jlong, jobject, jobject);

/*
 * Class:     domain_engine_quantum_maps_NativeMap
 * Method:    _putAll
 * Signature: (JLjava/util/Map;)V
 */
JNIEXPORT void JNICALL Java_domain_engine_quantum_maps_NativeMap__1putAll
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     domain_engine_quantum_maps_NativeMap
 * Method:    _remove
 * Signature: (JLjava/lang/Object;)Ldomain/engine/math/Complex;
 */
JNIEXPORT jobject JNICALL Java_domain_engine_quantum_maps_NativeMap__1remove
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     domain_engine_quantum_maps_NativeMap
 * Method:    _size
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_domain_engine_quantum_maps_NativeMap__1size
  (JNIEnv *, jobject, jlong);

/*
 * Class:     domain_engine_quantum_maps_NativeMap
 * Method:    _values
 * Signature: (J)Ljava/util/Collection;
 */
JNIEXPORT jobject JNICALL Java_domain_engine_quantum_maps_NativeMap__1values
  (JNIEnv *, jobject, jlong);


#ifdef __cplusplus
}
#endif
#endif
